# Generated by Django 5.2.6 on 2025-10-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application_email_application_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], default='full-time', max_length=20),
        ),
    ]
