# Generated by Django 5.2.6 on 2025-10-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_requirements_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the application', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', '📝 Pending'), ('reviewed', '👀 Reviewed'), ('interview', '💼 Interview'), ('rejected', '❌ Rejected'), ('accepted', '✅ Accepted')], default='pending', max_length=20),
        ),
    ]
